name: E2E Tests

on: [push, pull_request]

jobs:
  test:
    name: Running e2e Tests with npm
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install npm
      run: npm install
    - name: Running E2E Tests
      run: npm run e2e-test
    - name: Slack Notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: npmTestBot
